[workspace]
members = [
    "helix-db",
    "helix-container",
    "helix-macros",
    "helix-cli",
    "hql-tests",
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.44.2", features = ["full"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.140"
chrono = { version = "0.4.39", features = ["serde"] }
uuid = { version = "1.12.1", features = ["v4", "v6", "fast-rng", "std"] }
dirs = "5.0.1"
tempfile = "3.20.0"
heed3 = "0.22.0"
sonic-rs = "0.5.0"
rand = "0.9.0"
inventory = "0.3.16"
async-trait = "0.1.88"
tracing = "0.1.41"
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
dotenvy = "0.15.7"
reqwest = { version = "0.12.15", features = ["json", "blocking"] }
tracing-subscriber = "0.3.19"

[profile.release]
opt-level = 2
codegen-units = 1
lto = true
panic = "abort"
strip = "debuginfo"

[profile.dev]
opt-level = 0
codegen-units = 256
lto = false
panic = "abort"
incremental = true
debug = 1

