[package]
name = "helix-container"
version = "0.1.0"
edition = "2024"

[dependencies]
helix-db = { path = "../helix-db" }
helix-macros = { path = "../helix-macros" }

inventory = { workspace = true }
rand = { workspace = true }
dirs = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
sonic-rs = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
heed3 = { workspace = true }
async-trait = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
dotenvy = { workspace = true }
