[package]
name = "hql-tests"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "test"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
futures = "0.3"
octocrab = "0.44.1"
serde = { workspace = true }
sha2 = "0.10"
base64 = "0.22" 